version: '3'

services:
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - 7100:7100
    environment:
      NODE_ENV: production
      PORT: 7100
      LOG_LEVEL: info
      JWT_SECRET: verylongrandomstring
      DATABASE_URL: postgresql://pg-user:pg-password@host.docker.internal:5102/local_quarterback_db?schema=public
    restart: always
  postgres:
    image: postgres:13.4-alpine
    ports:
      - 5102:5432
    environment:
      POSTGRES_PASSWORD: pg-password
      POSTGRES_USER: pg-user
      POSTGRES_DB: local_quarterback_db
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

networks:
  default:
    name: example-local