name: pnpm
description: Setup pnpm and install dependencies
inputs:
  cache: # id of input
    description: Path of the pnpm cache
    required: true
    default: .pnpm-store

runs:
  using: composite
  steps:
    - name: Install pnpm
      run: npm i pnpm@7 -g
      shell: bash

    - name: Setup pnpm config
      run: pnpm config set store-dir ${{ inputs.cache }}
      shell: bash

    - name: Install dependencies
      run: pnpm i --frozen-lockfile
      shell: bash
