name: Create new changeset PR

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  CI: true

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies with pnpm
        uses: ./.github/actions/pnpm.yml

      - name: Build packages
        run: pnpm build
    
      - name: Create versions
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: 'chore(changeset): version update'
          title: 'chore(changeset): version update'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}